#!/bin/sh

# Set these paths appropriately

BIN=/auto_home/rcolin/Documents/M1/HMIN208/Project/lib/bin
CMD=/auto_home/rcolin/Documents/M1/HMIN208/Project/lib/cmd
LIB=/auto_home/rcolin/Documents/M1/HMIN208/Project/lib/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize-korean.pl
PARFILE=${LIB}/korean-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE |
$CMD/add-korean-sentence-markers.pl |
$CMD/reformat-korean-tagger-output.pl
