#!/bin/sh

# Set these paths appropriately

BIN=/auto_home/rcolin/Documents/M1/HMIN208/Project/lib/bin
CMD=/auto_home/rcolin/Documents/M1/HMIN208/Project/lib/cmd
LIB=/auto_home/rcolin/Documents/M1/HMIN208/Project/lib/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
