#!/bin/sh

# Set these paths appropriately

BIN=/auto_home/rcolin/Documents/M1/HMIN208/Project/lib/bin
CMD=/auto_home/rcolin/Documents/M1/HMIN208/Project/lib/cmd
LIB=/auto_home/rcolin/Documents/M1/HMIN208/Project/lib/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/catalan-abbreviations
PARFILE=${LIB}/catalan-utf8.par

$TOKENIZER -c -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
